use strict; use warnings;
# usage: perl gen_iocdata.pl ctx697096_check.sh [ips]   (mode 'ips' = only the IP tables, used by cmd/ipxref)
my $sh = shift; my $mode = shift // ''; open(my $f,'<',$sh) or die; my @L = <$f>; close $f;
sub ln { $L[$_[0]-1] }
sub ips { my @r = ln($_[0]) =~ /\b(\d{1,3}(?:\.\d{1,3}){3})\b/g; @r }
sub hx { my @r = ln($_[0]) =~ /\b([0-9a-f]{64})\b/g; @r }
my %ipl = (
 978=>'GreyNoise / Marius Sandbu / Lupovis / Mandiant-GTIG',
 980=>'Gotham Technology Group (download servers, senders)',
 983=>'PitScaler.com compilation (Truesec, eSentire, IFIN, Corelight, Lupovis)',
 985=>'Arctic Wolf alert pack',
 987=>'Unit 42',
 989=>'TENEX (Platypus C2, gsocket/netcat wave)',
 993=>'SAML-dropper exfil host / Sygnia / LevelBlue SpiderLabs',
 996=>'Unit 42 update / Rapid7',
 998=>'NetScaler community (2 Oct)',
 1002=>'Gotham IR (2 Oct)', 1003=>'Gotham IR (2 Oct)', 1004=>'Gotham IR (2 Oct)', 1005=>'Gotham IR (2 Oct)',
 1008=>'Beazley Security second wave',
 1010=>'feiglein74 (pitboss injection source, PR #1)',
);
print "// Code generated by gen.pl from ctx697096_check.sh. DO NOT EDIT.\n";
print "// Source: https://github.com/ThomasPoppelgaard/netscaler-ctx697096-checker (script v1.12)\n\n";
print "package main\n\n";
print "type iocIP struct{ IP, Source string }\n\n";
print "var attackerIPs = []iocIP{\n";
my %seen;
for my $n (sort {$a<=>$b} keys %ipl) { for my $ip (ips($n)) { next if $seen{$ip}++; print "\t{\"$ip\", \"$ipl{$n}\"},\n"; } }
print "}\n\n";
# opportunistic scanners
my $o = ln(1022); my @op; while ($o =~ /(\d{1,3}(?:\\\.\d{1,3}){3})/g) { my $x=$1; $x =~ s/\\//g; push @op,$x }
print "var scannerIPs = []string{\n"; my %s2; for my $x (@op) { next if $s2{$x}++ || $seen{$x}; print "\t\"$x\",\n"; } print "}\n\n";
exit 0 if $mode eq 'ips';
# domains
my ($dl) = ln(1014) =~ /GN_DOM='([^']+)'/; my @dom = map { s/\\//gr } split /\|/, $dl;
print "var attackerDomains = []string{\n"; print "\t\"$_\",\n" for @dom; print "}\n\n";
# hashes
print "type iocHash struct{ SHA256, Source string }\n\n";
print "var knownHashes = []iocHash{\n";
my %hs; my @h = (
 [976,'GreyNoise .ctxs.receiver webshell'],
 [1038,'IFIN / eSentire webshell samples (via PitScaler.com)'],
 [1040,'Arctic Wolf (xd7h/x, nsmon.pl, update_c08937.pl, Platypus script)'],
 [1042,'Unit 42 webshell / package / payload samples (via Deyda)'],
 [1044,'LevelBlue main.py (/var/1.py)'],
 [1046,'SAML-attack dropper 380d56 (2 Oct)'],
 [1049,'/v script, SAML kit gen 2/3, chisel, Sliver, Perl payload (Gotham / ThreatUnpacked)'],
 [1176,'Platypus C2 agent (TENEX)'],
);
for my $e (@h) { for my $x (hx($e->[0])) { next if $hs{$x}++; print "\t{\"$x\", \"$e->[1]\"},\n"; } }
print "}\n\n";
my ($vh) = hx(971);
print "// vulnerableMonuploaddHash is the vulnerable ns_monuploadd_err.pl (14.1-66.59 / 72.61).\nconst vulnerableMonuploaddHash = \"$vh\"\n";
